
name: CI plugin test

on:
  push:
    branches:
      #TODO run on versioned branches only
      - "7.16"
jobs:
  ci:

    runs-on: ubuntu-latest

    #TODO ES image should be ${{github.ref_name}}.[0, 1, 2, 3]
    env:
      ES_IMAGE: docker.elastic.co/elasticsearch/elasticsearch:7.16.3


    steps:
      #TODO first 2 steps are same as in release-from-tag, maybe better way of reuse?
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: -Ptag=${{github.ref_name}} pluginZip

    - name: Pull elastic docker image
      run: docker pull $ES_IMAGE

    - name: Run elastic with plugin
      run: |
        docker run --detach \
        --user 1000:1000 \
        -p 127.0.0.1:9200:9200 -p 127.0.0.1:9300:9300   \
        -v $(realpath docker-entrypoint-es-plugin.sh):/opt/docker/start.sh \
        -v $(realpath build/distributions):/plugin/distributions \
        -e "traveltime.app.id=${{ secrets.TTP_ID }}"     -e "traveltime.api.key=${{ secrets.TTP_KEY }}" \
        -e "discovery.type=single-node" \
        --entrypoint=/bin/bash \
        $ES_IMAGE \
        /opt/docker/start.sh

      #TODO figure out if there is a proper way to wait for ES to go up or timeout
    - name: wait 30s for elasticsearch to go up
      run: |
        sleep 30
#      ES has a healthcheck endpoint, maybe that can be used
#      run: curl -XGET http://localhost:9200/_cluster/health?pretty=true&timeout=30s

    - name: curl at elasticsearch
      run: curl http://localhost:9200
