name: Integration Test

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - '**.md'

jobs:
  test-image:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        esVersion:
          - "7.10"
          - "7.11"
          - "7.12"
          - "7.13"
          - "7.14"
          - "7.15"
          - "7.16"
          - "7.17"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
          - "8.6"
          - "8.7"
          - "8.8"
          - "8.9"
          - "8.10"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Run integration test with gradle
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: ${{ matrix.esVersion }}:dockerTest
